import type { Row, CellChange } from "@/types/sheet";

interface CsvExportOptions {
  delimiter?: string;
  includeHeaders?: boolean;
  watermark?: boolean;
}

export function exportToCSV(
  rows: Row[],
  headers: string[],
  options: CsvExportOptions = {}
): string {
  const { delimiter = ",", includeHeaders = true, watermark = false } = options;
  const lines: string[] = [];

  if (includeHeaders) {
    lines.push(headers.map((h) => escapeCSV(h, delimiter)).join(delimiter));
  }

  for (const row of rows) {
    const values = headers.map((h) => escapeCSV(String(row[h] ?? ""), delimiter));
    lines.push(values.join(delimiter));
  }

  if (watermark) {
    lines.push("");
    lines.push(`${escapeCSV("Cleaned with TidySheet — tidysheet.com", delimiter)}`);
  }

  return lines.join("\n");
}

export function exportChangeLog(
  changes: CellChange[],
  watermark = false
): string {
  const headers = ["Row", "Column", "Original Value", "Cleaned Value", "Rule", "Type", "Timestamp"];
  const lines = [headers.join(",")];

  for (const c of changes) {
    lines.push(
      [
        c.rowIndex === -1 ? "Header" : String(c.rowIndex + 1),
        escapeCSV(c.column),
        escapeCSV(String(c.originalValue ?? "")),
        escapeCSV(String(c.newValue ?? "")),
        escapeCSV(c.ruleName),
        c.changeType,
        new Date(c.timestamp).toISOString(),
      ].join(",")
    );
  }

  if (watermark) {
    lines.push("");
    lines.push(escapeCSV("Generated by TidySheet — tidysheet.com"));
  }

  return lines.join("\n");
}

export function exportQuarantined(
  rows: { originalIndex: number; row: Row; reason: string; ruleId: string }[],
  headers: string[]
): string {
  if (rows.length === 0) return "";

  const allHeaders = ["Original Row", ...headers, "Reason", "Rule"];
  const lines = [allHeaders.join(",")];

  for (const q of rows) {
    const values = [
      String(q.originalIndex + 1),
      ...headers.map((h) => escapeCSV(String(q.row[h] ?? ""))),
      escapeCSV(q.reason),
      escapeCSV(q.ruleId),
    ];
    lines.push(values.join(","));
  }

  return lines.join("\n");
}

/** Characters that spreadsheet apps interpret as formula starters — prevent CSV injection */
const FORMULA_PREFIXES = ["=", "+", "-", "@", "\t", "\r"];

function escapeCSV(value: string, delimiter = ","): string {
  let escaped = value;

  // Prevent CSV injection: prefix formula-triggering characters with a single quote
  if (escaped.length > 0 && FORMULA_PREFIXES.some((p) => escaped.startsWith(p))) {
    escaped = "'" + escaped;
  }

  if (escaped.includes(",") || escaped.includes('"') || escaped.includes("\n") || escaped.includes(delimiter)) {
    return `"${escaped.replace(/"/g, '""')}"`;
  }
  return escaped;
}
