import type { CellChange, QuarantinedRow, HealthReport } from "@/types/sheet";

interface SummaryData {
  fileName: string;
  originalRowCount: number;
  cleanedRowCount: number;
  changes: CellChange[];
  quarantined: QuarantinedRow[];
  healthReport: HealthReport | null;
  rulesApplied: string[];
}

export function exportSummary(data: SummaryData): string {
  const lines: string[] = [];
  const hr = "─".repeat(50);

  lines.push("TIDYSHEET CLEANING SUMMARY");
  lines.push(hr);
  lines.push(`File: ${data.fileName}`);
  lines.push(`Date: ${new Date().toISOString()}`);
  lines.push("");

  lines.push("OVERVIEW");
  lines.push(hr);
  lines.push(`Original rows:     ${data.originalRowCount.toLocaleString()}`);
  lines.push(`Cleaned rows:      ${data.cleanedRowCount.toLocaleString()}`);
  lines.push(`Rows removed:      ${(data.originalRowCount - data.cleanedRowCount).toLocaleString()}`);
  lines.push(`Cells changed:     ${data.changes.length.toLocaleString()}`);
  lines.push(`Rows quarantined:  ${data.quarantined.length.toLocaleString()}`);
  lines.push(`Rules applied:     ${data.rulesApplied.length}`);
  lines.push("");

  if (data.healthReport) {
    lines.push("HEALTH REPORT");
    lines.push(hr);
    lines.push(`Issues found: ${data.healthReport.totalIssues}`);
    lines.push(`  HIGH:   ${data.healthReport.highCount}`);
    lines.push(`  MEDIUM: ${data.healthReport.mediumCount}`);
    lines.push(`  LOW:    ${data.healthReport.lowCount}`);
    lines.push("");

    for (const issue of data.healthReport.issues) {
      lines.push(`  [${issue.severity}] ${issue.title}: ${issue.description}`);
      for (const ex of issue.examples.slice(0, 2)) {
        lines.push(`    → ${ex}`);
      }
    }
    lines.push("");
  }

  lines.push("RULES APPLIED");
  lines.push(hr);
  for (const rule of data.rulesApplied) {
    lines.push(`  • ${rule}`);
  }
  lines.push("");

  // Changes by rule
  const changesByRule = new Map<string, number>();
  for (const c of data.changes) {
    changesByRule.set(c.ruleName, (changesByRule.get(c.ruleName) ?? 0) + 1);
  }

  lines.push("CHANGES BY RULE");
  lines.push(hr);
  for (const [rule, count] of changesByRule) {
    lines.push(`  ${rule}: ${count.toLocaleString()} changes`);
  }
  lines.push("");

  lines.push(hr);
  lines.push("Generated by TidySheet — tidysheet.com");

  return lines.join("\n");
}
