import {
  pgTable,
  text,
  integer,
  boolean,
  timestamp,
  date,
  index,
} from "drizzle-orm/pg-core";

// ─── Users ───────────────────────────────────────────────────────────────────
export const users = pgTable(
  "users",
  {
    id: text("id").primaryKey(), // Clerk user ID
    email: text("email").notNull(),
    name: text("name"),
    stripeCustomerId: text("stripe_customer_id"),
    plan: text("plan", { enum: ["free", "pro", "team"] })
      .notNull()
      .default("free"),
    subscriptionStatus: text("subscription_status", {
      enum: ["active", "past_due", "canceled", "trialing", "incomplete"],
    }),
    stripeSubscriptionId: text("stripe_subscription_id"),
    currentPeriodEnd: timestamp("current_period_end"),
    exportsToday: integer("exports_today").notNull().default(0),
    exportsResetDate: date("exports_reset_date")
      .notNull()
      .defaultNow(),
    teamId: text("team_id"),
    teamRole: text("team_role", { enum: ["admin", "member"] }),
    createdAt: timestamp("created_at").notNull().defaultNow(),
    updatedAt: timestamp("updated_at").notNull().defaultNow(),
  },
  (table) => [index("users_email_idx").on(table.email)]
);

// ─── Teams ───────────────────────────────────────────────────────────────────
export const teams = pgTable("teams", {
  id: text("id").primaryKey(), // UUID generated by app
  name: text("name").notNull(),
  ownerId: text("owner_id")
    .notNull()
    .references(() => users.id),
  stripeSubscriptionId: text("stripe_subscription_id"),
  seatCount: integer("seat_count").notNull().default(1),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

// ─── Presets ─────────────────────────────────────────────────────────────────
export const presets = pgTable(
  "presets",
  {
    id: text("id").primaryKey(), // UUID generated by app
    userId: text("user_id")
      .notNull()
      .references(() => users.id),
    teamId: text("team_id").references(() => teams.id),
    name: text("name").notNull(),
    description: text("description").notNull().default(""),
    rules: text("rules").notNull(), // JSON string
    isShared: boolean("is_shared").notNull().default(false),
    createdAt: timestamp("created_at").notNull().defaultNow(),
    updatedAt: timestamp("updated_at").notNull().defaultNow(),
  },
  (table) => [index("presets_user_id_idx").on(table.userId)]
);

// ─── Audit Logs ──────────────────────────────────────────────────────────────
export const auditLogs = pgTable(
  "audit_logs",
  {
    id: text("id").primaryKey(),
    teamId: text("team_id")
      .notNull()
      .references(() => teams.id),
    userId: text("user_id")
      .notNull()
      .references(() => users.id),
    action: text("action").notNull(),
    presetId: text("preset_id"),
    metadata: text("metadata"), // JSON — NO file contents
    createdAt: timestamp("created_at").notNull().defaultNow(),
  },
  (table) => [index("audit_logs_team_id_idx").on(table.teamId)]
);

// ─── Export Logs ─────────────────────────────────────────────────────────────
export const exportLogs = pgTable(
  "export_logs",
  {
    id: text("id").primaryKey(),
    userId: text("user_id")
      .notNull()
      .references(() => users.id),
    fileName: text("file_name").notNull(), // Name only, no contents
    rowCount: integer("row_count").notNull(),
    rulesApplied: text("rules_applied").notNull(), // JSON array of rule IDs
    exportedAt: timestamp("exported_at").notNull().defaultNow(),
  },
  (table) => [index("export_logs_user_id_idx").on(table.userId)]
);
